AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DWCOA Financial Tracker - Serverless financial management for condo association

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12
    Environment:
      Variables:
        DATA_BUCKET: !Ref DataBucket
        POWERTOOLS_SERVICE_NAME: dwcoa-financials

Parameters:
  AdminPasswordHash:
    Type: String
    Description: Bcrypt hash of admin password
    NoEcho: true
    Default: ""
  BoardPasswordHash:
    Type: String
    Description: Bcrypt hash of board password
    NoEcho: true
    Default: ""
  AnthropicApiKey:
    Type: String
    Description: Anthropic API key for Claude
    NoEcho: true
    Default: ""
  JwtSecret:
    Type: String
    Description: Secret for signing JWT tokens
    NoEcho: true
    Default: ""

Resources:
  # S3 Bucket for data storage (SQLite, uploads)
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dwcoa-data-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 Bucket for frontend static hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dwcoa-frontend-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Bucket policy to allow public read for frontend
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"

  # Lambda function for API
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dwcoa-api
      CodeUri: backend/
      Handler: app.main.handler
      Description: DWCOA Financial Tracker API
      Environment:
        Variables:
          ADMIN_PASSWORD_HASH: !Ref AdminPasswordHash
          BOARD_PASSWORD_HASH: !Ref BoardPasswordHash
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY

  # HTTP API Gateway
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With
        MaxAge: 600

  # CloudFront distribution for frontend
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
          - Id: ApiOrigin
            DomainName: !Sub "${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: /prod
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac  # AllViewerExceptHostHeader
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  FrontendBucket:
    Description: S3 bucket for frontend files
    Value: !Ref FrontendBucket
  FrontendUrl:
    Description: S3 website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
  CloudFrontUrl:
    Description: CloudFront distribution URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
  DataBucket:
    Description: S3 bucket for data storage
    Value: !Ref DataBucket
